// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://knzlybklpnewyddtyavi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtuemx5YmtscG5ld3lkZHR5YXZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NDM3MDEsImV4cCI6MjA2MTIxOTcwMX0.bl6SCSHyAonpNiY63IVdmubuP1fS47KSO9XlWe_zwiU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);